fix: add `@verdaccio/core` as a dependency
`@verdaccio/core` is needed as a runtime dependency. See: https://github.com/verdaccio/verdaccio/blob/31a18f8f613925abe89ed37b19f227ce25da9c1b/packages/loaders/src/utils.ts#L3

```
Error: Cannot find module '@verdaccio/core'
Require stack:
- /home/runner/.cache/bazel/_bazel_runner/f47b8283cc0f5922f9455b06771398a1/sandbox/processwrapper-sandbox/3053/execroot/_main/bazel-out/k8-fastbuild/bin/tests/legacy-cli/e2e.esbuild_node22_/e2e.esbuild_node22.runfiles/_main/node_modules/.aspect_rules_js/@verdaccio+loaders@8.0.0-next-8.7/node_modules/@verdaccio/loaders/build/plugin-async-loader.js
```